name: Install dependencies (robust)

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  appium-tests:
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [android, ios]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (robust)
        run: |
          echo "Attempting clean CI install..."
          npm ci || (echo "Lockfile mismatch detected — running npm install fallback" && rm -rf node_modules && npm install)

      # --- ANDROID SETUP ---
      - name: Set up Android environment
        if: matrix.platform == 'android'
        run: |
          echo "Setting up Android emulator"
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;google_apis;x86_64"
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n testEmulator -k "system-images;android-30;google_apis;x86_64" --force
          nohup $ANDROID_HOME/emulator/emulator -avd testEmulator -no-audio -no-snapshot -no-window &
          adb wait-for-device
          adb shell input keyevent 82

      # --- IOS SETUP ---
      - name: Boot iOS simulator
        if: matrix.platform == 'ios'
        run: |
          xcrun simctl list devices
          SIMULATOR=$(xcrun simctl create "iPhone-14-Test" "com.apple.CoreSimulator.SimDeviceType.iPhone-14" "com.apple.CoreSimulator.SimRuntime.iOS-17-0")
          xcrun simctl boot $SIMULATOR
          xcrun simctl bootstatus $SIMULATOR

      # --- START APPIUM SERVER ---
      - name: Start Appium server
        run: |
          npx appium --log-level info &
          sleep 10

      # --- RUN TESTS ---
      - name: Run Appium tests (${{ matrix.platform }})
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          echo "Running Appium tests on $PLATFORM"
          npx wdio wdio.${{ matrix.platform }}.conf.js --spec ./tests/${{ matrix.platform }}

      # --- UPLOAD RESULTS ---
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-${{ matrix.platform }}-report
          path: reports/${{ matrix.platform }}/
